### ISSUE TITLE
How to use this repo

### ISSUE THREAD

**Issue by s00500** [eigger/hass-niimbot#1]
Hey, super cool project,

Any tipps on how to use it ? So far I tried adding it on HACS but it does not show up. After that I have pushed the folder in custom_components to my HA. When I select it in the Integrations page I get an 
`Config flow could not be loaded: {"message":"Invalid handler specified"}`
Error...

Any Tipps ?

**Comment by eigger** [comment]
Just add it to HACS. What version of Home Assistant are you using? I tested it on Home Assistant version 2024.09. The HACS version I'm using is 2.0.1
<img width="1180" alt="스크린샷 2024-09-07 오전 8 46 44" src="https://github.com/user-attachments/assets/f907a6a0-29b8-4409-83f8-6a2a37acd8db">

**Comment by s00500** [comment]
Hey, cool stuff, yes, seems like it took some time to show up ... config flow works too, will test when I am back home, thanks a lot !
